version: '3.7'

volumes:
  odoo14-web-data:
  odoo14-db-data:

services:
  # Web Application Service Definition
  # --------
  #
  # All of the information needed to start up an odoo web
  # application container.
  odoo14:
    image: odoo:14.0
    depends_on:
        - db1

    # Port Mapping
    # --------
    #
    # Here we are mapping a port on the host machine (on the left)
    # to a port inside of the container (on the right.) The default
    # port on Odoo is 8069, so Odoo is running on that port inside
    # of the container. But we are going to access it locally on
    # our machine from localhost:9000.
    ports:
      - 9000:8069

    # Data Volumes
    # --------
    #
    # This defines files that we are mapping from the host machine
    # into the container.
    #
    # Right now, we are using it to map a configuration file into
    # the container and any extra odoo modules.
    volumes:
      - ./config:/etc/odoo
      - ./external_addons:/mnt/external_addons
      - odoo14-web-data:/var/lib/odoo
    # Odoo Environment Variables
    # --------
    #
    # The odoo image uses a few different environment
    # variables when running to connect to the postgres
    # database.
    #
    # Make sure that they are the same as the database user
    # defined in the db container environment variables.
    environment:
      - HOST=db1
      - USER=odoo14
      - PASSWORD=odoo14

  # Database Container Service Definition
  # --------
  #
  # All of the information needed to start up a postgresql
  # container.
  db1:
    image: postgres:12

    # Database Environment Variables
    # --------
    #
    # The postgresql image uses a few different environment
    # variables when running to create the database. Set the
    # username and password of the database user here.
    #
    # Make sure that they are the same as the database user
    # defined in the web container environment variables.
    environment:
      - POSTGRES_PASSWORD=odoo14
      - POSTGRES_USER=odoo14
      - POSTGRES_DB=postgres  # Leave this set to postgres
      - PGDATA=/var/lib/postgresql/data/pgdata

    volumes:
      - odoo14-db-data:/var/lib/postgresql/data/pgdata

    ports:
      - 5432:5432